import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  Alert, AppBar, Box, Button, Card, CardContent, Checkbox, Chip, Container, CssBaseline, Dialog, DialogActions,
  DialogContent, DialogTitle, Divider, Drawer, FormControl, FormControlLabel, Grid, InputLabel, List,
  ListItemButton, ListItemText, MenuItem, Paper, Select, Snackbar, Stack, Tab, Tabs, Table, TableBody,
  TableCell, TableContainer, TableHead, TableRow, TextField, ThemeProvider, Toolbar, Typography,
} from '@mui/material';
import theme, { severityColors } from './theme';
import {
  addAction, closeFindingApi, convertDefenderCve, convertDefenderMachine, createFinding, defenderExportUrl,
  deleteFinding, exportUrl, getActions, getDashboard, getDefenderDashboard, getDefenderMachines,
  getDefenderRecommendations, getDefenderSettings, getDefenderVulnerabilities, getFindings, getLogs,
  importExcel, previewExcel, reopenFindingApi, syncDefenderAll, testDefenderConnection, updateDefenderSettings,
  updateFinding,
} from './api';

const LOGO_SRC = '/assets/surat-logo.svg';
const DRAWER_WIDTH = 292;
const severities = ['Acil', 'Kritik', 'Yüksek', 'Orta', 'Düşük'];
const statuses = ['Devam Ediyor', 'Kapatıldı'];
const navigationItems = ['Gösterge Paneli', 'Bulgular', 'Bulgu Ekle', 'Excel ile Bulgu Ekle', 'Microsoft CVE / MSRC', 'Defender Zafiyetleri', 'Raporlar', 'Ayarlar'];
const emptyFinding = { record_no: '', title: '', severity: 'Orta', impact: '', description: '', recommendation: '', related_unit: '', related_person: '', status: 'Devam Ediyor', due_date: '', new_due_date: '', note: '', source: 'Manuel' };

function formatDate(value) { return value ? new Date(value).toLocaleString('tr-TR') : '-'; }
function formatDay(value) { return value ? new Date(value).toLocaleDateString('tr-TR') : '-'; }
function BrandLogo({ height = 40 }) { return <Box component="img" src={LOGO_SRC} alt="Sürat Kargo" sx={{ display: 'block', height, maxHeight: height, maxWidth: '100%', objectFit: 'contain' }} />; }
function SeverityChip({ severity }) { return <Chip label={severity || '-'} size="small" sx={{ minWidth: 72, bgcolor: severityColors[severity] || { Critical: '#991b1b', High: '#dc2626', Medium: '#f59e0b', Low: '#16a34a' }[severity] || 'primary.main', color: severity === 'Orta' || severity === 'Medium' ? '#1f2937' : '#fff', fontWeight: 800 }} />; }
function SummaryCard({ label, value, helper, accent = 'primary.main' }) { return <Card sx={{ height: '100%' }}><CardContent><Stack direction="row" justifyContent="space-between" spacing={2}><Box><Typography color="text.secondary" variant="body2" fontWeight={700}>{label}</Typography><Typography variant="h4" fontWeight={900} sx={{ mt: .5 }}>{value ?? '-'}</Typography></Box><Box sx={{ width: 10, height: 54, borderRadius: 10, bgcolor: accent }} /></Stack>{helper && <Typography color="text.secondary" variant="caption" sx={{ display: 'block', mt: 1.5 }}>{helper}</Typography>}</CardContent></Card>; }
function SectionHeader({ title, description }) { return <Box sx={{ mb: 2.5 }}><Typography variant="h5" color="primary.dark">{title}</Typography><Typography color="text.secondary" sx={{ mt: .5 }}>{description}</Typography></Box>; }

function DataTable({ title, rows = [], columns, actions }) {
  return <Paper sx={{ p: 2.5, height: '100%', border: '1px solid rgba(15, 47, 87, 0.08)' }}><Typography variant="h6" sx={{ mb: 2 }}>{title}</Typography><TableContainer><Table size="small"><TableHead><TableRow>{columns.map((c) => <TableCell key={c.key}>{c.label}</TableCell>)}{actions && <TableCell>İşlem</TableCell>}</TableRow></TableHead><TableBody>{rows.length ? rows.map((row, i) => <TableRow hover key={row.id || row.cve_id || row.recommendation_id || i}>{columns.map((c) => <TableCell key={c.key}>{c.render ? c.render(row) : (row[c.key] ?? '-')}</TableCell>)}{actions && <TableCell>{actions(row)}</TableCell>}</TableRow>) : <TableRow><TableCell colSpan={columns.length + (actions ? 1 : 0)}>Kayıt yok.</TableCell></TableRow>}</TableBody></Table></TableContainer></Paper>;
}

function Dashboard({ summary }) {
  const d = summary || {};
  const defender = d.defender_summary || {};
  const cards = [
    ['Toplam Bulgu', d.total, 'Tüm kayıtlar'], ['Açık Kalan', d.open, 'Kapatılmamış kayıtlar'], ['Kapatılan', d.closed, 'Tamamlanan kayıtlar'],
    ['Kritik', d.severity_counts?.Kritik || 0, 'Kritik seviye', severityColors.Kritik], ['Yüksek', d.severity_counts?.Yüksek || 0, 'Yüksek seviye', severityColors.Yüksek], ['Geciken Bulgular', d.overdue || d.delayed || 0, 'Aktif termini geçmiş'],
  ];
  return <Stack spacing={3}><SectionHeader title="Gösterge Paneli" description="Bulgular, SLA durumu ve Defender zafiyet özetleri." />
    <Grid container spacing={2}>{cards.map(([label, value, helper, accent]) => <Grid item xs={12} sm={6} md={4} lg={2} key={label}><SummaryCard label={label} value={value} helper={helper} accent={accent} /></Grid>)}</Grid>
    <Paper sx={{ p: 2.5 }}><Typography variant="h6" sx={{ mb: 2 }}>Microsoft Defender Özeti</Typography><Grid container spacing={2}>{[
      ['Defender Toplam CVE', defender.total_cve || 0], ['Kritik Defender CVE', defender.critical_cve || 0], ['Yüksek Defender CVE', defender.high_cve || 0], ['Etkilenen Cihaz Sayısı', defender.affected_machines || 0], ['Public Exploit', defender.public_exploit || 0], ['Bulguya Dönüştürülen Defender CVE', defender.converted_findings || 0],
    ].map(([label, value]) => <Grid item xs={12} md={2} key={label}><SummaryCard label={label} value={value} /></Grid>)}</Grid></Paper>
    <Grid container spacing={2}><Grid item xs={12} md={6}><DataTable title="Geciken Bulgular" rows={d.overdue_findings || []} columns={[{ key: 'record_no', label: 'Kayıt No' }, { key: 'title', label: 'Başlık' }, { key: 'severity', label: 'Seviye', render: (r) => <SeverityChip severity={r.severity} /> }, { key: 'active_due_date', label: 'Termin', render: (r) => formatDay(r.active_due_date) }]} /></Grid><Grid item xs={12} md={6}><DataTable title="Termin Yaklaşanlar" rows={d.approaching_due || []} columns={[{ key: 'record_no', label: 'Kayıt No' }, { key: 'title', label: 'Başlık' }, { key: 'severity', label: 'Seviye', render: (r) => <SeverityChip severity={r.severity} /> }, { key: 'active_due_date', label: 'Termin', render: (r) => formatDay(r.active_due_date) }]} /></Grid></Grid>
  </Stack>;
}

function FindingForm({ initial = emptyFinding, onSubmit, submitLabel = 'Kaydet' }) {
  const [form, setForm] = useState({ ...emptyFinding, ...initial });
  const set = (key, value) => setForm((f) => ({ ...f, [key]: value }));
  const submit = (e) => { e.preventDefault(); onSubmit({ ...form, due_date: form.due_date || null, new_due_date: form.new_due_date || null }); };
  return <Box component="form" onSubmit={submit}><Grid container spacing={2}>{[
    ['record_no', 'Kayıt No'], ['title', 'Bulgu Başlığı'], ['related_unit', 'İlgili Birim / Kurum'], ['related_person', 'İlgili Kişi'], ['due_date', 'Termin Tarih', 'date'], ['new_due_date', 'Yeni Termin', 'date'],
  ].map(([key, label, type]) => <Grid item xs={12} md={6} key={key}><TextField fullWidth required={key === 'record_no'} type={type || 'text'} label={label} value={form[key] || ''} onChange={(e) => set(key, e.target.value)} InputLabelProps={type ? { shrink: true } : undefined} /></Grid>)}
    <Grid item xs={12} md={6}><FormControl fullWidth><InputLabel>Durum Seviyesi</InputLabel><Select label="Durum Seviyesi" value={form.severity} onChange={(e) => set('severity', e.target.value)}>{severities.map((x) => <MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl></Grid>
    <Grid item xs={12} md={6}><FormControl fullWidth><InputLabel>Durum</InputLabel><Select label="Durum" value={form.status} onChange={(e) => set('status', e.target.value)}>{statuses.map((x) => <MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl></Grid>
    {['impact', 'description', 'recommendation', 'note'].map((key) => <Grid item xs={12} key={key}><TextField fullWidth multiline minRows={2} label={{ impact: 'Bulgunun Etkisi', description: 'Bulgunun Açıklaması', recommendation: 'Çözüm Önerisi', note: 'Notlar' }[key]} value={form[key] || ''} onChange={(e) => set(key, e.target.value)} /></Grid>)}
    <Grid item xs={12}><Button type="submit" variant="contained">{submitLabel}</Button></Grid></Grid></Box>;
}

function FindingsPage({ findings, refresh, show }) {
  const [detail, setDetail] = useState(null); const [editing, setEditing] = useState(null);
  const saveEdit = async (payload) => { try { await updateFinding(editing.id, payload); setEditing(null); show('Bulgu güncellendi.', 'success'); refresh(); } catch (e) { show(e.message, 'error'); } };
  return <><SectionHeader title="Bulgular" description="İç bulgu kayıtları, durum ve aksiyon işlemleri." /><DataTable title="Bulgu Listesi" rows={findings} columns={[{ key: 'record_no', label: 'Kayıt No' }, { key: 'title', label: 'Başlık' }, { key: 'severity', label: 'Seviye', render: (r) => <SeverityChip severity={r.severity} /> }, { key: 'related_unit', label: 'Birim' }, { key: 'status', label: 'Durum' }, { key: 'active_due_date', label: 'Termin', render: (r) => formatDay(r.active_due_date) }]} actions={(r) => <Stack direction="row" spacing={1}><Button size="small" onClick={() => setDetail(r)}>Detay</Button><Button size="small" onClick={() => setEditing(r)}>Düzenle</Button><Button size="small" onClick={async () => { await (r.status === 'Kapatıldı' ? reopenFindingApi(r.id) : closeFindingApi(r.id)); refresh(); }}>{r.status === 'Kapatıldı' ? 'Aç' : 'Kapat'}</Button><Button size="small" color="error" onClick={async () => { await deleteFinding(r.id); refresh(); }}>Sil</Button></Stack>} />
    <FindingDetail finding={detail} onClose={() => setDetail(null)} show={show} />
    <Dialog open={Boolean(editing)} onClose={() => setEditing(null)} maxWidth="md" fullWidth><DialogTitle>Bulgu Düzenle</DialogTitle><DialogContent dividers>{editing && <FindingForm initial={editing} onSubmit={saveEdit} submitLabel="Güncelle" />}</DialogContent><DialogActions><Button onClick={() => setEditing(null)}>Vazgeç</Button></DialogActions></Dialog></>;
}

function FindingDetail({ finding, onClose, show }) {
  const [actions, setActions] = useState([]);
  useEffect(() => { if (finding) getActions(finding.id).then(setActions).catch((e) => show(e.message, 'error')); }, [finding?.id]);
  return <Dialog open={Boolean(finding)} onClose={onClose} maxWidth="md" fullWidth><DialogTitle>{finding?.record_no} Detayı</DialogTitle><DialogContent dividers><Stack spacing={2}><Typography variant="h6">{finding?.title}</Typography><Typography>{finding?.description}</Typography><DataTable title="Aksiyon Geçmişi" rows={actions} columns={[{ key: 'created_at', label: 'Tarih', render: (r) => formatDate(r.created_at) }, { key: 'action_type', label: 'Tip' }, { key: 'note', label: 'Not' }, { key: 'created_by', label: 'Kullanıcı' }]} /></Stack></DialogContent><DialogActions><Button onClick={onClose}>Kapat</Button></DialogActions></Dialog>;
}

function ExcelImportPage({ onImported, show }) {
  const [file, setFile] = useState(null); const [preview, setPreview] = useState(null);
  return <Paper sx={{ p: 3 }}><SectionHeader title="Excel ile Bulgu Ekle" description="Mevcut import/export yapısını kullanarak Bulgular sayfasını içe aktarın." /><Stack direction="row" spacing={2} alignItems="center"><Button variant="outlined" component="label">Dosya Seç<input hidden type="file" accept=".xlsx,.xlsm" onChange={(e) => setFile(e.target.files?.[0])} /></Button><Typography>{file?.name || 'Dosya seçilmedi'}</Typography><Button disabled={!file} onClick={async () => { try { setPreview(await previewExcel(file)); } catch (e) { show(e.message, 'error'); } }}>Önizle</Button><Button variant="contained" disabled={!file} onClick={async () => { try { onImported(await importExcel(file)); } catch (e) { show(e.message, 'error'); } }}>İçe Aktar</Button></Stack>{preview && <Alert sx={{ mt: 2 }} severity="info">{preview.total} kayıt önizlendi, {preview.failed} hata.</Alert>}</Paper>;
}

function MsrcPage() { return <Paper sx={{ p: 3 }}><SectionHeader title="Microsoft CVE / MSRC" description="Mevcut MSRC entegrasyonu korunmuştur. Defender eşleştirmeleri CVE ID üzerinden Defender detay ekranında gösterilir." /><Alert severity="info">Bu aşama Defender Vulnerability Management entegrasyonudur; MSRC ekranı mevcut yapıyı bozmamak için ayrı tutuldu.</Alert></Paper>; }

function DefenderPage({ show, refreshApp }) {
  const [tab, setTab] = useState(0); const [dashboard, setDashboard] = useState({}); const [vulns, setVulns] = useState([]); const [machines, setMachines] = useState([]); const [recs, setRecs] = useState([]); const [detail, setDetail] = useState(null);
  const load = async () => { const [d, v, m, r] = await Promise.all([getDefenderDashboard(), getDefenderVulnerabilities(), getDefenderMachines(), getDefenderRecommendations()]); setDashboard(d); setVulns(v.items || []); setMachines(m.items || []); setRecs(r.items || []); };
  useEffect(() => { load().catch((e) => show(e.message, 'error')); }, []);
  const convertCve = async (row) => { try { const res = await convertDefenderCve(row.cve_id); show(res.message || 'Defender CVE bulguya dönüştürüldü.', res.status === 'duplicate' ? 'warning' : 'success'); refreshApp(); } catch (e) { show(e.message, 'error'); } };
  const convertMachine = async (row) => { try { const res = await convertDefenderMachine({ cve_id: row.cve_id, machine_id: row.machine_id }); show(res.message || 'Defender cihaz zafiyeti bulguya dönüştürüldü.', res.status === 'duplicate' ? 'warning' : 'success'); refreshApp(); } catch (e) { show(e.message, 'error'); } };
  const topCards = [['Toplam CVE', dashboard.total_cve], ['Kritik CVE', dashboard.critical_cve], ['Yüksek CVE', dashboard.high_cve], ['Etkilenen Cihaz', dashboard.affected_machines], ['Açıkta Olan Uygulama', dashboard.exposed_applications], ['Public Exploit Olanlar', dashboard.public_exploit], ['Verified Exploit Olanlar', dashboard.verified_exploit], ['Remediation Bekleyenler', dashboard.pending_remediation], ['Son Sync', dashboard.last_sync ? formatDate(dashboard.last_sync) : '-']];
  return <Stack spacing={2.5}><SectionHeader title="Defender Zafiyetleri" description="Microsoft Defender Vulnerability Management CVE, cihaz/yazılım ve remediation görünümü." />{dashboard.demo && <Alert severity="warning">Defender entegrasyonu yapılandırılmadı. Gösterilen veriler demo amaçlıdır.</Alert>}<Stack direction="row" spacing={1}><Button variant="contained" onClick={() => load().then(() => show('Defender verileri yenilendi.', 'success'))}>Yenile</Button><Button variant="outlined" href={defenderExportUrl()}>Excel Export</Button></Stack><Grid container spacing={2}>{topCards.map(([label, value]) => <Grid item xs={12} sm={6} md={4} lg={2.4} key={label}><SummaryCard label={label} value={value ?? 0} /></Grid>)}</Grid>
    <Grid container spacing={2}><Grid item xs={12} md={4}><DataTable title="Severity Dağılımı" rows={dashboard.severity_distribution || []} columns={[{ key: 'name', label: 'Severity' }, { key: 'count', label: 'Adet' }]} /></Grid><Grid item xs={12} md={4}><DataTable title="En Çok Açık Görülen Uygulamalar" rows={dashboard.top_applications || []} columns={[{ key: 'name', label: 'Uygulama' }, { key: 'count', label: 'Adet' }]} /></Grid><Grid item xs={12} md={4}><DataTable title="En Çok Etkilenen Cihazlar" rows={dashboard.top_machines || []} columns={[{ key: 'name', label: 'Cihaz' }, { key: 'count', label: 'Adet' }]} /></Grid><Grid item xs={12} md={4}><DataTable title="Üretici Bazlı Açık Dağılımı" rows={dashboard.vendor_distribution || []} columns={[{ key: 'name', label: 'Üretici' }, { key: 'count', label: 'Adet' }]} /></Grid><Grid item xs={12} md={4}><DataTable title="CVE Trendi" rows={dashboard.cve_trend || []} columns={[{ key: 'name', label: 'Tarih' }, { key: 'count', label: 'Adet' }]} /></Grid><Grid item xs={12} md={4}><DataTable title="Remediation Önerileri Dağılımı" rows={dashboard.recommendation_distribution || []} columns={[{ key: 'name', label: 'Tip' }, { key: 'count', label: 'Adet' }]} /></Grid></Grid>
    <Paper><Tabs value={tab} onChange={(_, v) => setTab(v)} variant="scrollable"><Tab label="CVE Listesi" /><Tab label="Cihaz/Yazılım Zafiyetleri" /><Tab label="Öneriler" /></Tabs></Paper>
    {tab === 0 && <DataTable title="Defender CVE Listesi" rows={vulns} columns={[{ key: 'cve_id', label: 'CVE ID' }, { key: 'description', label: 'Açıklama' }, { key: 'severity', label: 'Severity', render: (r) => <SeverityChip severity={r.severity} /> }, { key: 'cvss_v3', label: 'CVSS' }, { key: 'exposed_machines', label: 'Etkilenen Cihaz' }, { key: 'public_exploit', label: 'Public Exploit', render: (r) => r.public_exploit ? 'Evet' : 'Hayır' }, { key: 'exploit_verified', label: 'Verified Exploit', render: (r) => r.exploit_verified ? 'Evet' : 'Hayır' }, { key: 'epss', label: 'EPSS' }, { key: 'published_on', label: 'Yayınlanma', render: (r) => formatDay(r.published_on) }, { key: 'updated_on', label: 'Güncellenme', render: (r) => formatDay(r.updated_on) }, { key: 'status', label: 'Durum' }, { key: 'msrc_match', label: 'MSRC', render: (r) => r.msrc_match ? <Chip label="MSRC Var" color="success" size="small" /> : <Chip label="MSRC kaydı bulunamadı" size="small" /> }]} actions={(r) => <Stack direction="row" spacing={1}><Button size="small" onClick={() => setDetail({ type: 'cve', row: r })}>Detay Gör</Button><Button size="small" onClick={() => convertCve(r)}>Bulguya Dönüştür</Button><Button size="small" onClick={() => setDetail({ type: 'msrc', row: r })}>MSRC ile Eşleştir</Button></Stack>} />}
    {tab === 1 && <DataTable title="Cihaz/Yazılım Zafiyetleri" rows={machines} columns={[{ key: 'machine_name', label: 'Cihaz Adı' }, { key: 'machine_id', label: 'Cihaz ID' }, { key: 'cve_id', label: 'CVE ID' }, { key: 'product_vendor', label: 'Üretici' }, { key: 'product_name', label: 'Uygulama' }, { key: 'product_version', label: 'Versiyon' }, { key: 'severity', label: 'Severity', render: (r) => <SeverityChip severity={r.severity} /> }, { key: 'fixing_kb_id', label: 'Fixing KB' }, { key: 'recommendation_id', label: 'Recommendation ID' }, { key: 'remediation_status', label: 'Remediation Status' }, { key: 'first_seen', label: 'İlk Görülme', render: (r) => formatDay(r.first_seen) }, { key: 'last_seen', label: 'Son Görülme', render: (r) => formatDay(r.last_seen) }]} actions={(r) => <Stack direction="row" spacing={1}><Button size="small" onClick={() => setDetail({ type: 'machine', row: r })}>Detay Gör</Button><Button size="small" onClick={() => convertMachine(r)}>Bulguya Dönüştür</Button></Stack>} />}
    {tab === 2 && <DataTable title="Defender Önerileri" rows={recs} columns={[{ key: 'recommendation_id', label: 'Recommendation ID' }, { key: 'recommendation_name', label: 'Öneri Adı' }, { key: 'product_name', label: 'Ürün' }, { key: 'vendor', label: 'Üretici' }, { key: 'recommendation_category', label: 'Kategori' }, { key: 'severity_score', label: 'Severity Score' }, { key: 'exposed_machines', label: 'Etkilenen Cihaz' }, { key: 'remediation_type', label: 'Remediation Type' }, { key: 'status', label: 'Status' }, { key: 'exposure_impact', label: 'Exposure Impact' }]} actions={() => <Button size="small">Detay Gör</Button>} />}
    <DefenderDetail detail={detail} onClose={() => setDetail(null)} machines={machines} recommendations={recs} />
  </Stack>;
}

function DefenderDetail({ detail, onClose, machines, recommendations }) {
  const [tab, setTab] = useState(0); const row = detail?.row || {}; const affected = machines.filter((m) => m.cve_id === row.cve_id); const recs = recommendations.filter((r) => r.recommendation_id === row.recommendation_id || r.product_name === row.product_name);
  return <Dialog open={Boolean(detail)} onClose={onClose} maxWidth="lg" fullWidth><DialogTitle>Defender Detayı - {row.cve_id || row.recommendation_id}</DialogTitle><DialogContent dividers><Tabs value={tab} onChange={(_, v) => setTab(v)} variant="scrollable"><Tab label="Genel Bilgi" /><Tab label="Etkilenen Cihazlar" /><Tab label="Etkilenen Yazılımlar" /><Tab label="Remediation" /><Tab label="MSRC Eşleşmesi" /><Tab label="Ham Veri" /></Tabs><Box sx={{ mt: 2 }}>{tab === 0 && <pre>{JSON.stringify(row, null, 2)}</pre>}{tab === 1 && <DataTable title="Etkilenen Cihazlar" rows={affected} columns={[{ key: 'machine_name', label: 'Cihaz' }, { key: 'machine_id', label: 'ID' }, { key: 'severity', label: 'Severity' }]} />}{tab === 2 && <DataTable title="Etkilenen Yazılımlar" rows={affected} columns={[{ key: 'product_vendor', label: 'Üretici' }, { key: 'product_name', label: 'Uygulama' }, { key: 'product_version', label: 'Versiyon' }]} />}{tab === 3 && <DataTable title="Remediation" rows={recs} columns={[{ key: 'recommendation_id', label: 'ID' }, { key: 'recommendation_name', label: 'Öneri' }, { key: 'remediation_type', label: 'Tip' }]} />}{tab === 4 && <Alert severity={row.msrc_match ? 'success' : 'info'}>{row.msrc_match ? 'MSRC Var' : 'MSRC kaydı bulunamadı'}</Alert>}{tab === 5 && <pre>{JSON.stringify(row.raw || row, null, 2)}</pre>}</Box></DialogContent><DialogActions><Button onClick={onClose}>Kapat</Button></DialogActions></Dialog>;
}

function Reports({ findings }) {
  const rows = [
    ['Kritik/Yüksek Defender CVE Raporu', 'Defender ekranından Excel export ile alınabilir.'], ['Uygulama Bazlı Zafiyet Raporu', 'Defender_Cihaz_Yazilim_CVE sayfası kullanılır.'], ['Cihaz Bazlı Zafiyet Raporu', 'Cihaz adına göre filtrelenmiş rapor.'], ['Public Exploit Olan CVE Raporu', 'Public exploit kolonu Evet olanlar.'], ['Remediation Bekleyenler Raporu', 'Remediation status açık/pending olanlar.'], ['Defender’dan Bulguya Dönüştürülenler Raporu', `${findings.filter((f) => f.source === 'Defender').length} kayıt`],
  ];
  return <Stack spacing={2}><SectionHeader title="Raporlar" description="Bulgular ve Defender raporları Excel’e aktarılabilir." /><Button variant="contained" href={exportUrl()}>Ana Bulgular Excel Export</Button><Button variant="outlined" href={defenderExportUrl()}>Defender Excel Export</Button><DataTable title="Defender Raporları" rows={rows.map(([name, desc], id) => ({ id, name, desc }))} columns={[{ key: 'name', label: 'Rapor' }, { key: 'desc', label: 'Açıklama' }]} /></Stack>;
}

function SettingsPage({ show }) {
  const [settings, setSettings] = useState({ tenant_id: '', client_id: '', client_secret: '', api_base_url: 'https://api.security.microsoft.com', integration_enabled: false });
  const load = async () => setSettings(await getDefenderSettings());
  useEffect(() => { load().catch((e) => show(e.message, 'error')); }, []);
  const set = (k, v) => setSettings((s) => ({ ...s, [k]: v }));
  return <Paper sx={{ p: 3 }}><SectionHeader title="Ayarlar" description="Microsoft Defender entegrasyonu ve bağlantı bilgileri." /><Alert severity="info" sx={{ mb: 2 }}>Defender entegrasyonu için Microsoft Entra uygulaması ve gerekli API izinleri tanımlanmalıdır.</Alert><Grid container spacing={2}><Grid item xs={12} md={6}><TextField fullWidth label="Tenant ID" value={settings.tenant_id || ''} onChange={(e) => set('tenant_id', e.target.value)} /></Grid><Grid item xs={12} md={6}><TextField fullWidth label="Client ID" value={settings.client_id || ''} onChange={(e) => set('client_id', e.target.value)} /></Grid><Grid item xs={12} md={6}><TextField fullWidth type="password" label="Client Secret" placeholder={settings.client_secret || 'Client Secret'} onChange={(e) => set('client_secret', e.target.value)} helperText="Kaydedildikten sonra maskeli gösterilir; frontendde açık gösterilmez." /></Grid><Grid item xs={12} md={6}><TextField fullWidth label="Defender API Base URL" value={settings.api_base_url || ''} onChange={(e) => set('api_base_url', e.target.value)} /></Grid><Grid item xs={12}><FormControlLabel control={<Checkbox checked={Boolean(settings.integration_enabled)} onChange={(e) => set('integration_enabled', e.target.checked)} />} label="Entegrasyon Aktif / Pasif" /></Grid><Grid item xs={12}><Typography><b>Son Sync Zamanı:</b> {formatDate(settings.last_sync_time)}</Typography><Typography><b>Son Test:</b> {settings.last_test_status} - {settings.last_test_message}</Typography><Typography><b>Gerekli izinler:</b> Vulnerability.Read.All, SecurityRecommendation.Read.All</Typography></Grid><Grid item xs={12}><Stack direction="row" spacing={1}><Button variant="contained" onClick={async () => { try { await updateDefenderSettings(settings); show('Defender ayarları kaydedildi.', 'success'); load(); } catch (e) { show(e.message, 'error'); } }}>Kaydet</Button><Button variant="outlined" onClick={async () => { try { const r = await testDefenderConnection(); show(r.message, 'success'); load(); } catch (e) { show(e.message, 'error'); } }}>Bağlantıyı Test Et</Button><Button variant="outlined" onClick={async () => { try { await syncDefenderAll(); show('Tüm Defender verileri senkronize edildi.', 'success'); load(); } catch (e) { show(e.message, 'error'); } }}>Tüm Verileri Senkronize Et</Button></Stack></Grid></Grid></Paper>;
}

function LogsPage() { const [logs, setLogs] = useState([]); useEffect(() => { getLogs().then(setLogs).catch(() => setLogs([])); }, []); return <DataTable title="İşlem Logları" rows={logs} columns={[{ key: 'created_at', label: 'Tarih', render: (r) => formatDate(r.created_at) }, { key: 'event_type', label: 'İşlem Tipi' }, { key: 'message', label: 'Mesaj' }, { key: 'detail', label: 'Detay' }, { key: 'created_by', label: 'Kullanıcı' }]} />; }

function App() {
  const [tab, setTab] = useState(0); const [summary, setSummary] = useState(null); const [findings, setFindings] = useState([]); const [message, setMessage] = useState(''); const [severity, setSeverity] = useState('info');
  const show = (text, sev = 'info') => { setMessage(text); setSeverity(sev); };
  const refresh = async () => { try { const [dashboard, rows] = await Promise.all([getDashboard(), getFindings()]); setSummary(dashboard); setFindings(rows); } catch (e) { show(e.message, 'error'); } };
  useEffect(() => { refresh(); }, []);
  const saveNew = async (payload) => { try { await createFinding(payload); show('Bulgu başarıyla kaydedildi.', 'success'); setTab(1); refresh(); } catch (e) { show(e.message, 'error'); } };
  const content = () => {
    if (tab === 0) return <Dashboard summary={summary} />;
    if (tab === 1) return <FindingsPage findings={findings} refresh={refresh} show={show} />;
    if (tab === 2) return <Paper sx={{ p: 3 }}><SectionHeader title="Bulgu Ekle" description="Yeni güvenlik bulgusunu arka uç API üzerinden kaydedin." /><FindingForm onSubmit={saveNew} /></Paper>;
    if (tab === 3) return <ExcelImportPage show={show} onImported={(r) => { show(`İçe aktarma tamamlandı: ${r.created} yeni, ${r.updated} güncellendi, ${r.failed} hatalı`, r.failed ? 'warning' : 'success'); refresh(); }} />;
    if (tab === 4) return <MsrcPage />;
    if (tab === 5) return <DefenderPage show={show} refreshApp={refresh} />;
    if (tab === 6) return <Reports findings={findings} />;
    return <SettingsPage show={show} />;
  };
  return <ThemeProvider theme={theme}><CssBaseline /><Box sx={{ bgcolor: 'background.default', display: 'flex', minHeight: '100vh' }}><AppBar position="fixed" sx={{ zIndex: (muiTheme) => muiTheme.zIndex.drawer + 1 }}><Toolbar sx={{ gap: 2, minHeight: 72 }}><BrandLogo height={40} /><Box sx={{ flexGrow: 1 }}><Typography variant="h6" noWrap>Siber Risk ve Bulgu Yönetimi</Typography></Box><Button color="inherit" href={exportUrl()} variant="contained" sx={{ bgcolor: 'rgba(255,255,255,.15)' }}>Excel Dışa Aktar</Button></Toolbar></AppBar><Drawer variant="permanent" sx={{ width: DRAWER_WIDTH, flexShrink: 0, [`& .MuiDrawer-paper`]: { width: DRAWER_WIDTH, boxSizing: 'border-box', bgcolor: '#fff', borderRight: '1px solid rgba(15, 47, 87, 0.10)' } }}><Toolbar sx={{ minHeight: 88, justifyContent: 'center', px: 3 }}><BrandLogo height={40} /></Toolbar><Divider /><Box sx={{ p: 2 }}><Typography variant="caption" color="text.secondary" fontWeight={800} sx={{ display: 'block', textAlign: 'center', letterSpacing: .8 }}>MENÜ</Typography><List sx={{ mt: 1.5 }}>{navigationItems.map((item, index) => <ListItemButton key={item} selected={tab === index} onClick={() => setTab(index)} sx={{ borderRadius: 2.5, mb: 1, minHeight: 52, py: 1.05, px: 2, justifyContent: 'center', textAlign: 'center', '&.Mui-selected': { bgcolor: 'primary.main', color: 'primary.contrastText', boxShadow: '0 10px 22px rgba(15, 47, 87, .20)', '&:hover': { bgcolor: 'primary.dark' } } }}><ListItemText primary={item} secondary={index === 1 ? `${findings.length} kayıt` : index === 0 ? 'Genel görünüm' : null} sx={{ m: 0, textAlign: 'center' }} primaryTypographyProps={{ fontWeight: 800, textAlign: 'center' }} secondaryTypographyProps={{ textAlign: 'center', fontSize: 12, color: tab === index ? 'rgba(255,255,255,.78)' : 'text.secondary' }} /></ListItemButton>)}</List></Box></Drawer><Box component="main" sx={{ flexGrow: 1, minWidth: 0 }}><Toolbar sx={{ minHeight: 72 }} /><Container maxWidth="xl" sx={{ py: 3.5 }}>{content()}</Container></Box><Snackbar open={Boolean(message)} autoHideDuration={6000} onClose={() => setMessage('')}><Alert severity={severity} onClose={() => setMessage('')}>{message}</Alert></Snackbar></Box></ThemeProvider>;
}

createRoot(document.getElementById('root')).render(<App />);
