import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  Alert, AppBar, Box, Button, Card, CardContent, Checkbox, Chip, Container, CssBaseline, Dialog,
  DialogActions, DialogContent, DialogTitle, Divider, Drawer, FormControl, FormControlLabel, Grid,
  InputLabel, List, ListItemButton, ListItemText, MenuItem, Paper, Select, Snackbar, Stack, Tab, Tabs,
  Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, ThemeProvider, Toolbar,
  Typography,
} from '@mui/material';
import { addAction, bulkClose, bulkUpdate, closeFindingApi, createFinding, deleteFinding, exportUrl, getActions, getDashboard, getFindings, getLogs, importExcel, previewExcel, reopenFindingApi, updateFinding } from './api';
import theme, { severityColors } from './theme';

const LOGO_SRC = '/assets/surat-logo.svg';
const DRAWER_WIDTH = 292;
const severities = ['Acil', 'Kritik', 'Yüksek', 'Orta', 'Düşük'];
const statuses = ['Devam Ediyor', 'Kapatıldı'];
const slaStatuses = ['Kapalı', 'Gecikti', 'Yaklaşıyor', 'Zamanında'];
const emptyFinding = { record_no: '', title: '', severity: 'Orta', impact: '', description: '', recommendation: '', related_unit: '', related_person: '', status: 'Devam Ediyor', due_date: '', new_due_date: '', note: '', source: 'Manuel' };
const navigationItems = ['Dashboard', 'Bulgular', 'Bulgu Ekle', 'Excel ile Bulgu Ekle', 'Raporlar', 'İşlem Logları'];
const reportOptions = [
  ['critical', 'Açık Kritik / Yüksek Bulgular'], ['overdue', 'Geciken Bulgular'], ['dueSoon', 'Termin Yaklaşan Bulgular'],
  ['closed', 'Kapatılan Bulgular'], ['unit', 'İlgili Birim / Kurum Bazlı Özet'], ['person', 'İlgili Kişi Bazlı Özet'],
];

function formatDate(value) { return value ? new Date(value).toLocaleString('tr-TR') : ''; }
function formatDay(value) { return value ? new Date(value).toLocaleDateString('tr-TR') : '-'; }
function BrandLogo({ height = 40 }) { return <Box component="img" src={LOGO_SRC} alt="Sürat Kargo" sx={{ display: 'block', height, maxHeight: height, maxWidth: '100%', objectFit: 'contain' }} />; }
function SeverityChip({ severity }) { return <Chip label={severity} size="small" sx={{ minWidth: 72, bgcolor: severityColors[severity] || 'primary.main', color: severity === 'Orta' ? '#1f2937' : '#fff', fontWeight: 800 }} />; }
function SlaChip({ value }) { const map = { Kapalı: ['#dcfce7', '#166534'], Gecikti: ['#fee2e2', '#991b1b'], Yaklaşıyor: ['#fef3c7', '#92400e'], Zamanında: ['#dbeafe', '#1e40af'] }; const [bg, color] = map[value] || map.Zamanında; return <Chip label={value || '-'} size="small" sx={{ bgcolor: bg, color, fontWeight: 800 }} />; }
function SummaryCard({ label, value, helper, accent = 'primary.main' }) { return <Card sx={{ height: '100%' }}><CardContent><Stack direction="row" justifyContent="space-between" spacing={2}><Box><Typography color="text.secondary" variant="body2" fontWeight={700}>{label}</Typography><Typography variant="h4" fontWeight={900} sx={{ mt: .5 }}>{value ?? '-'}</Typography></Box><Box sx={{ width: 10, height: 54, borderRadius: 10, bgcolor: accent }} /></Stack>{helper && <Typography color="text.secondary" variant="caption" sx={{ display: 'block', mt: 1.5 }}>{helper}</Typography>}</CardContent></Card>; }
function SectionHeader({ title, description }) { return <Box sx={{ mb: 2.5 }}><Typography variant="h5" color="primary.dark">{title}</Typography><Typography color="text.secondary" sx={{ mt: .5 }}>{description}</Typography></Box>; }

function DataTable({ title, rows = [], columns }) {
  return <Paper sx={{ p: 2.5, height: '100%', border: '1px solid rgba(15, 47, 87, 0.08)' }}><Typography variant="h6" sx={{ mb: 2 }}>{title}</Typography><TableContainer><Table size="small"><TableHead><TableRow>{columns.map((c) => <TableCell key={c.key}>{c.label}</TableCell>)}</TableRow></TableHead><TableBody>{rows.length ? rows.map((row, i) => <TableRow key={row.id || row.name || i}>{columns.map((c) => <TableCell key={c.key}>{c.render ? c.render(row) : row[c.key]}</TableCell>)}</TableRow>) : <TableRow><TableCell colSpan={columns.length}>Kayıt yok.</TableCell></TableRow>}</TableBody></Table></TableContainer></Paper>;
}

function Dashboard({ summary }) {
  const data = summary || {};
  const tableCols = [
    { key: 'record_no', label: 'Kayıt No' }, { key: 'title', label: 'Bulgu Başlığı' }, { key: 'severity', label: 'Seviye', render: (r) => <SeverityChip severity={r.severity} /> },
    { key: 'related_unit', label: 'İlgili Birim / Kurum' }, { key: 'related_person', label: 'İlgili Kişi' }, { key: 'active_due_date', label: 'Aktif Termin', render: (r) => formatDay(r.active_due_date) }, { key: 'delay_days', label: 'Gecikme Günü' },
  ];
  const cards = [
    ['Toplam Bulgu', data.total, 'Tüm kayıtlar'], ['Açık Kalan', data.open, 'Kapatılmamış kayıtlar'], ['Kapatılan', data.closed, 'Tamamlanan kayıtlar'],
    ['Acil', data.severity_counts?.Acil || 0, 'Acil seviye', severityColors.Acil], ['Kritik', data.severity_counts?.Kritik || 0, 'Kritik seviye', severityColors.Kritik], ['Yüksek', data.severity_counts?.Yüksek || 0, 'Yüksek seviye', severityColors.Yüksek], ['Orta', data.severity_counts?.Orta || 0, 'Orta seviye', severityColors.Orta], ['Düşük', data.severity_counts?.Düşük || 0, 'Düşük seviye', severityColors.Düşük],
    ['Geciken Bulgular', data.overdue || data.delayed || 0, 'Aktif termini geçmiş'], ['Termin Yaklaşanlar', data.due_soon || 0, '7 gün içinde'], ['Bugün Kapananlar', data.today_closed || 0, 'Bugünkü kapanış'], ['Bu Hafta Kapananlar', data.week_closed || 0, 'Haftalık kapanış'], ['Kapanma Oranı', `%${data.closure_rate || 0}`, 'Kapanan / toplam'], ['Son Çalışma Saati', formatDate(data.last_work_time) || '-', 'Son işlem zamanı'],
  ];
  return <Stack spacing={3}>{data.demo && <Alert severity="info">Veritabanı boş olduğu için demo yerine gerçek metrikler 0 gösteriliyor. Bulgu ekleyin veya Excel import yapın.</Alert>}
    <Paper sx={{ p: 3, background: 'linear-gradient(135deg, rgba(15, 47, 87, 0.96), rgba(31, 90, 149, 0.9))', color: '#fff' }}><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="h4" fontWeight={900}>Aşama 2 Kurumsal Takip Paneli</Typography><Typography sx={{ opacity: .85, mt: .5 }}>Termin, SLA, aksiyon geçmişi, log ve toplu işlem görünümü.</Typography></Box><BrandLogo height={54} /></Stack></Paper>
    <Grid container spacing={2}>{cards.map(([label, value, helper, accent]) => <Grid item xs={12} sm={6} md={3} lg={2.4} key={label}><SummaryCard label={label} value={value} helper={helper} accent={accent} /></Grid>)}</Grid>
    <Grid container spacing={2}><Grid item xs={12} lg={6}><DataTable title="En Kritik Açık 10 Bulgu" rows={data.critical_open} columns={tableCols} /></Grid><Grid item xs={12} lg={6}><DataTable title="Geciken Bulgular" rows={data.overdue_findings} columns={tableCols} /></Grid><Grid item xs={12} lg={6}><DataTable title="Termin Yaklaşanlar" rows={data.approaching_due} columns={tableCols} /></Grid><Grid item xs={12} md={6} lg={3}><DataTable title="Birim Bazlı Açık Bulgular" rows={data.open_by_unit} columns={[{ key: 'name', label: 'Birim / Kurum' }, { key: 'count', label: 'Açık' }]} /></Grid><Grid item xs={12} md={6} lg={3}><DataTable title="Kişi Bazlı Açık Bulgular" rows={data.open_by_person} columns={[{ key: 'name', label: 'İlgili Kişi' }, { key: 'count', label: 'Açık' }]} /></Grid></Grid>
  </Stack>;
}

function FindingForm({ initial = emptyFinding, onSubmit, submitLabel = 'Kaydet' }) {
  const [form, setForm] = useState({ ...emptyFinding, ...initial, due_date: initial.due_date || '', new_due_date: initial.new_due_date || '' });
  const set = (key, value) => setForm((f) => ({ ...f, [key]: value }));
  const submit = (e) => { e.preventDefault(); const payload = { ...form, due_date: form.due_date || null, new_due_date: form.new_due_date || null }; delete payload.id; delete payload.created_at; delete payload.updated_at; delete payload.closed_at; delete payload.active_due_date; delete payload.sla_status; delete payload.delay_days; delete payload.last_action_at; delete payload.last_action_note; onSubmit(payload); };
  return <Box component="form" onSubmit={submit}><Grid container spacing={2}><Grid item xs={12} md={3}><TextField required fullWidth label="Kayıt No" value={form.record_no} onChange={(e) => set('record_no', e.target.value)} /></Grid><Grid item xs={12} md={9}><TextField required fullWidth label="Bulgu Başlığı" value={form.title} onChange={(e) => set('title', e.target.value)} /></Grid><Grid item xs={12} md={3}><FormControl fullWidth><InputLabel>Durum Seviyesi</InputLabel><Select label="Durum Seviyesi" value={form.severity} onChange={(e) => set('severity', e.target.value)}>{severities.map((s) => <MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></FormControl></Grid><Grid item xs={12} md={3}><FormControl fullWidth><InputLabel>Durum</InputLabel><Select label="Durum" value={form.status} onChange={(e) => set('status', e.target.value)}>{statuses.map((s) => <MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></FormControl></Grid><Grid item xs={12} md={3}><TextField fullWidth type="date" label="Termin Tarih" InputLabelProps={{ shrink: true }} value={form.due_date || ''} onChange={(e) => set('due_date', e.target.value)} /></Grid><Grid item xs={12} md={3}><TextField fullWidth type="date" label="Yeni Termin" InputLabelProps={{ shrink: true }} value={form.new_due_date || ''} onChange={(e) => set('new_due_date', e.target.value)} /></Grid><Grid item xs={12} md={6}><TextField fullWidth label="İlgili Birim / Kurum" value={form.related_unit} onChange={(e) => set('related_unit', e.target.value)} /></Grid><Grid item xs={12} md={6}><TextField fullWidth label="İlgili Kişi" value={form.related_person} onChange={(e) => set('related_person', e.target.value)} /></Grid>{[['impact', 'Bulgunun Etkisi'], ['description', 'Bulgunun Açıklaması'], ['recommendation', 'Çözüm Önerisi'], ['note', 'Not']].map(([key, label]) => <Grid item xs={12} md={6} key={key}><TextField fullWidth multiline minRows={3} label={label} value={form[key] || ''} onChange={(e) => set(key, e.target.value)} /></Grid>)}<Grid item xs={12}><Stack direction="row" justifyContent="flex-end"><Button type="submit" variant="contained">{submitLabel}</Button></Stack></Grid></Grid></Box>;
}

function FilterBar({ filters, setFilters, refresh }) {
  const set = (key, value) => setFilters((f) => ({ ...f, [key]: value }));
  return <Paper sx={{ p: 2, mb: 2 }}><Grid container spacing={1.5} alignItems="center"><Grid item xs={12} md={2.3}><TextField fullWidth size="small" label="Arama" value={filters.search} onChange={(e) => set('search', e.target.value)} /></Grid><Grid item xs={6} md={1.6}><FormControl fullWidth size="small"><InputLabel>Seviye</InputLabel><Select label="Seviye" value={filters.severity} onChange={(e) => set('severity', e.target.value)}><MenuItem value="">Tümü</MenuItem>{severities.map((s) => <MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></FormControl></Grid><Grid item xs={6} md={1.6}><FormControl fullWidth size="small"><InputLabel>Durum</InputLabel><Select label="Durum" value={filters.status} onChange={(e) => set('status', e.target.value)}><MenuItem value="">Tümü</MenuItem>{statuses.map((s) => <MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></FormControl></Grid><Grid item xs={6} md={1.6}><FormControl fullWidth size="small"><InputLabel>SLA</InputLabel><Select label="SLA" value={filters.sla_status} onChange={(e) => set('sla_status', e.target.value)}><MenuItem value="">Tümü</MenuItem>{slaStatuses.map((s) => <MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></FormControl></Grid><Grid item xs={6} md={1.8}><TextField fullWidth size="small" label="Birim / Kurum" value={filters.related_unit} onChange={(e) => set('related_unit', e.target.value)} /></Grid><Grid item xs={6} md={1.8}><TextField fullWidth size="small" label="İlgili Kişi" value={filters.related_person} onChange={(e) => set('related_person', e.target.value)} /></Grid><Grid item xs={12} md={1.3}><Button fullWidth variant="outlined" onClick={refresh}>Yenile</Button></Grid><Grid item xs={12}><Stack direction="row" flexWrap="wrap" spacing={1}>{[['overdue', 'Gecikenler'], ['approaching_due', 'Termin Yaklaşanlar'], ['closed_only', 'Kapatılanlar'], ['open_only', 'Açık Kalanlar']].map(([key, label]) => <FormControlLabel key={key} control={<Checkbox checked={Boolean(filters[key])} onChange={(e) => set(key, e.target.checked)} />} label={label} />)}</Stack></Grid></Grid></Paper>;
}

function BulkBar({ selected, clear, refresh, show }) {
  const [status, setStatus] = useState(''); const [person, setPerson] = useState(''); const [due, setDue] = useState('');
  const ids = [...selected];
  const run = async (payload) => { await bulkUpdate({ ids, ...payload }); show('Toplu güncelleme tamamlandı.', 'success'); clear(); refresh(); };
  if (!ids.length) return null;
  return <Paper sx={{ p: 2, mb: 2, bgcolor: '#f8fafc' }}><Stack direction="row" spacing={1.5} alignItems="center" flexWrap="wrap"><Typography fontWeight={800}>{ids.length} seçim</Typography><FormControl size="small" sx={{ minWidth: 170 }}><InputLabel>Toplu Durum</InputLabel><Select label="Toplu Durum" value={status} onChange={(e) => setStatus(e.target.value)}>{statuses.map((s) => <MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></FormControl><Button variant="outlined" onClick={() => status && run({ status })}>Durum Güncelle</Button><TextField size="small" label="Toplu İlgili Kişi" value={person} onChange={(e) => setPerson(e.target.value)} /><Button variant="outlined" onClick={() => person && run({ related_person: person, assigned_to: person })}>Kişi Ata</Button><TextField size="small" type="date" label="Toplu Termin" InputLabelProps={{ shrink: true }} value={due} onChange={(e) => setDue(e.target.value)} /><Button variant="outlined" onClick={() => due && run({ new_due_date: due })}>Termin Güncelle</Button><Button color="error" variant="contained" onClick={async () => { await bulkClose(ids); show('Toplu kapatma tamamlandı.', 'success'); clear(); refresh(); }}>Toplu Kapat</Button><Button href={exportUrl(ids)} variant="contained">Seçili Excel</Button><Button onClick={clear}>Seçimi Temizle</Button></Stack></Paper>;
}

function FindingsTable({ findings, selected, setSelected, onEdit, onClose, onReopen, onDelete, onDetail }) {
  const toggle = (id) => setSelected((s) => { const n = new Set(s); n.has(id) ? n.delete(id) : n.add(id); return n; });
  return <TableContainer component={Paper}><Table size="small"><TableHead><TableRow><TableCell padding="checkbox"><Checkbox checked={findings.length > 0 && findings.every((f) => selected.has(f.id))} onChange={(e) => setSelected(e.target.checked ? new Set(findings.map((f) => f.id)) : new Set())} /></TableCell>{['Kayıt No', 'Bulgu Başlığı', 'Durum Seviyesi', 'Durum', 'SLA Durumu', 'Aktif Termin', 'Gecikme Günü', 'İlgili Birim / Kurum', 'İlgili Kişi', 'Son Aksiyon', 'Son Güncelleme', 'İşlemler'].map((h) => <TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{findings.map((f) => <TableRow hover key={f.id} onClick={() => onDetail(f)} sx={{ cursor: 'pointer', bgcolor: f.status === 'Kapatıldı' ? '#f0fdf4' : f.sla_status === 'Gecikti' ? '#fff1f2' : f.sla_status === 'Yaklaşıyor' ? '#fffbeb' : 'inherit' }}><TableCell padding="checkbox" onClick={(e) => e.stopPropagation()}><Checkbox checked={selected.has(f.id)} onChange={() => toggle(f.id)} /></TableCell><TableCell>{f.record_no}</TableCell><TableCell sx={{ minWidth: 220 }}>{f.title}</TableCell><TableCell><SeverityChip severity={f.severity} /></TableCell><TableCell>{f.status}</TableCell><TableCell><SlaChip value={f.sla_status} /></TableCell><TableCell>{formatDay(f.active_due_date)}</TableCell><TableCell>{f.delay_days || 0}</TableCell><TableCell>{f.related_unit}</TableCell><TableCell>{f.related_person}</TableCell><TableCell>{f.last_action_note}</TableCell><TableCell>{formatDate(f.updated_at)}</TableCell><TableCell onClick={(e) => e.stopPropagation()}><Stack direction="row" spacing={.5}><Button size="small" onClick={() => onEdit(f)}>Düzenle</Button>{f.status === 'Kapatıldı' ? <Button size="small" onClick={() => onReopen(f)}>Aç</Button> : <Button size="small" onClick={() => onClose(f)}>Kapat</Button>}<Button size="small" color="error" onClick={() => onDelete(f)}>Sil</Button></Stack></TableCell></TableRow>)}</TableBody></Table></TableContainer>;
}

function DetailDialog({ finding, onClose, refresh, show }) {
  const [tab, setTab] = useState(0); const [actions, setActions] = useState([]); const [note, setNote] = useState('');
  useEffect(() => { if (finding) getActions(finding.id).then(setActions).catch((e) => show(e.message, 'error')); }, [finding?.id]);
  if (!finding) return null;
  const addNote = async () => { await addAction(finding.id, { action_type: 'note_added', note }); setNote(''); setActions(await getActions(finding.id)); refresh(); show('Not eklendi.', 'success'); };
  return <Dialog open={Boolean(finding)} onClose={onClose} maxWidth="lg" fullWidth><DialogTitle>{finding.record_no} - Bulgu Detayı</DialogTitle><DialogContent dividers><Tabs value={tab} onChange={(_, v) => setTab(v)} sx={{ mb: 2 }}><Tab label="Genel Bilgiler" /><Tab label="Aksiyon Geçmişi" /><Tab label="Notlar" /><Tab label="Termin / SLA" /></Tabs>{tab === 0 && <Grid container spacing={2}>{[['Kayıt No', finding.record_no], ['Bulgu Başlığı', finding.title], ['Durum Seviyesi', finding.severity], ['Bulgunun Etkisi', finding.impact], ['Bulgunun Açıklaması', finding.description], ['Çözüm Önerisi', finding.recommendation], ['İlgili Birim / Kurum', finding.related_unit], ['İlgili Kişi', finding.related_person], ['Durum', finding.status], ['Termin Tarih', formatDay(finding.due_date)], ['Yeni Termin', formatDay(finding.new_due_date)], ['Not', finding.note]].map(([k, v]) => <Grid item xs={12} md={6} key={k}><Typography color="text.secondary" variant="caption">{k}</Typography><Typography fontWeight={700}>{v || '-'}</Typography></Grid>)}</Grid>}{tab === 1 && <DataTable title="Aksiyon Geçmişi" rows={actions} columns={[{ key: 'created_at', label: 'Tarih', render: (r) => formatDate(r.created_at) }, { key: 'action_type', label: 'İşlem Tipi' }, { key: 'old_value', label: 'Eski Değer' }, { key: 'new_value', label: 'Yeni Değer' }, { key: 'note', label: 'Not' }, { key: 'created_by', label: 'İşlemi Yapan' }]} />}{tab === 2 && <Stack spacing={2}><TextField fullWidth multiline minRows={4} label="Yeni Not" value={note} onChange={(e) => setNote(e.target.value)} /><Button variant="contained" disabled={!note.trim()} onClick={addNote}>Not Ekle</Button><DataTable title="Not Geçmişi" rows={actions.filter((a) => a.action_type === 'note_added' || a.note)} columns={[{ key: 'created_at', label: 'Tarih', render: (r) => formatDate(r.created_at) }, { key: 'note', label: 'Not' }, { key: 'created_by', label: 'Kullanıcı' }]} /></Stack>}{tab === 3 && <Grid container spacing={2}>{[['Aktif Termin', formatDay(finding.active_due_date)], ['SLA Durumu', finding.sla_status], ['Gecikme Günü', finding.delay_days || 0], ['Kapatılma Tarihi', formatDate(finding.closed_at)], ['Son Aksiyon Tarihi', formatDate(finding.last_action_at)]].map(([k, v]) => <Grid item xs={12} md={4} key={k}><Card><CardContent><Typography color="text.secondary">{k}</Typography><Typography variant="h6">{v || '-'}</Typography></CardContent></Card></Grid>)}</Grid>}</DialogContent><DialogActions><Button onClick={onClose}>Kapat</Button></DialogActions></Dialog>;
}

function ExcelImportPage({ onImported }) {
  const [file, setFile] = useState(null); const [preview, setPreview] = useState(null); const [error, setError] = useState('');
  const runPreview = async () => { setError(''); try { setPreview(await previewExcel(file)); } catch (e) { setError(e.message); } };
  const runImport = async () => { setError(''); try { onImported(await importExcel(file)); setPreview(null); setFile(null); } catch (e) { setError(e.message); } };
  return <Paper sx={{ p: 3 }}><SectionHeader title="Excel ile Bulgu Ekle" description="Mevcut Excel import/export akışı korunur; hatalı satırlar ve import logları gösterilir." />{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Stack direction="row" spacing={2} alignItems="center"><Button component="label" variant="contained">Excel Seç<input hidden type="file" accept=".xlsx,.xlsm" onChange={(e) => setFile(e.target.files?.[0])} /></Button><Typography>{file?.name || 'Dosya seçilmedi'}</Typography><Button disabled={!file} onClick={runPreview}>Önizle</Button><Button disabled={!file} onClick={runImport} variant="contained">İçe Aktar</Button><Button href={exportUrl()} variant="outlined">Şablon / Dışa Aktar</Button></Stack>{preview && <Box sx={{ mt: 3 }}><Alert severity={preview.failed ? 'warning' : 'success'}>{preview.total} kayıt okunacak, {preview.failed} hatalı satır.</Alert>{preview.errors?.length > 0 && <DataTable title="Import Hataları" rows={preview.errors} columns={[{ key: 'row', label: 'Satır' }, { key: 'message', label: 'Hata' }]} />}</Box>}</Paper>;
}

function Reports({ findings, summary }) {
  const [report, setReport] = useState('critical');
  const rows = useMemo(() => {
    if (report === 'critical') return findings.filter((f) => f.status !== 'Kapatıldı' && ['Acil', 'Kritik', 'Yüksek'].includes(f.severity));
    if (report === 'overdue') return findings.filter((f) => f.sla_status === 'Gecikti');
    if (report === 'dueSoon') return findings.filter((f) => f.sla_status === 'Yaklaşıyor');
    if (report === 'closed') return findings.filter((f) => f.status === 'Kapatıldı');
    return report === 'unit' ? summary?.open_by_unit || [] : summary?.open_by_person || [];
  }, [report, findings, summary]);
  const findingCols = [{ key: 'record_no', label: 'Kayıt No' }, { key: 'title', label: 'Bulgu Başlığı' }, { key: 'severity', label: 'Seviye' }, { key: 'status', label: 'Durum' }, { key: 'sla_status', label: 'SLA' }, { key: 'active_due_date', label: 'Aktif Termin', render: (r) => formatDay(r.active_due_date) }, { key: 'related_unit', label: 'Birim' }, { key: 'related_person', label: 'Kişi' }];
  return <Paper sx={{ p: 3 }}><SectionHeader title="Raporlar" description="Raporu ekranda görüntüleyin veya Excel olarak dışa aktarın." /><Stack direction="row" spacing={2} sx={{ mb: 2 }}><FormControl sx={{ minWidth: 280 }}><InputLabel>Rapor</InputLabel><Select label="Rapor" value={report} onChange={(e) => setReport(e.target.value)}>{reportOptions.map(([v, l]) => <MenuItem key={v} value={v}>{l}</MenuItem>)}</Select></FormControl><Button href={exportUrl(report === 'unit' || report === 'person' ? [] : rows.map((r) => r.id))} variant="contained">Excel’e Aktar</Button></Stack><DataTable title={reportOptions.find(([v]) => v === report)?.[1]} rows={rows} columns={report === 'unit' || report === 'person' ? [{ key: 'name', label: 'Ad' }, { key: 'count', label: 'Açık Bulgu' }] : findingCols} /></Paper>;
}

function LogsPage() { const [logs, setLogs] = useState([]); useEffect(() => { getLogs().then(setLogs).catch(() => setLogs([])); }, []); return <Paper sx={{ p: 3 }}><SectionHeader title="İşlem Logları" description="Excel, dashboard, bulgu ve hata olayları." /><DataTable title="Sistem Logları" rows={logs} columns={[{ key: 'created_at', label: 'Tarih', render: (r) => formatDate(r.created_at) }, { key: 'event_type', label: 'İşlem Tipi' }, { key: 'message', label: 'Mesaj' }, { key: 'detail', label: 'Detay' }, { key: 'created_by', label: 'Kullanıcı' }]} /></Paper>; }

function App() {
  const [tab, setTab] = useState(0); const [summary, setSummary] = useState(null); const [findings, setFindings] = useState([]); const [message, setMessage] = useState(''); const [severity, setSeverity] = useState('info'); const [detail, setDetail] = useState(null); const [editing, setEditing] = useState(null); const [selected, setSelected] = useState(new Set());
  const [filters, setFilters] = useState({ search: '', severity: '', status: '', sla_status: '', related_unit: '', related_person: '', approaching_due: false, overdue: false, open_only: false, closed_only: false });
  const show = (text, sev = 'info') => { setMessage(text); setSeverity(sev); };
  const refresh = async () => { try { const [dashboard, rows] = await Promise.all([getDashboard(), getFindings(filters)]); setSummary(dashboard); setFindings(rows); } catch (e) { show(e.message, 'error'); } };
  useEffect(() => { refresh(); }, [JSON.stringify(filters)]);
  const saveNew = async (payload) => { try { await createFinding(payload); show('Bulgu başarıyla kaydedildi.', 'success'); setTab(1); await refresh(); } catch (e) { show(e.message, 'error'); } };
  const saveEdit = async (payload) => { try { await updateFinding(editing.id, payload); setEditing(null); show('Bulgu güncellendi.', 'success'); await refresh(); } catch (e) { show(e.message, 'error'); } };
  const closeFinding = async (f) => { try { await closeFindingApi(f.id); show('Bulgu kapatıldı.', 'success'); await refresh(); } catch (e) { show(e.message, 'error'); } };
  const reopenFinding = async (f) => { try { await reopenFindingApi(f.id); show('Bulgu tekrar açıldı.', 'success'); await refresh(); } catch (e) { show(e.message, 'error'); } };
  const removeFinding = async (f) => { try { await deleteFinding(f.id); show('Bulgu silindi.', 'success'); await refresh(); } catch (e) { show(e.message, 'error'); } };
  const content = () => { if (tab === 0) return <Dashboard summary={summary} />; if (tab === 1) return <><SectionHeader title="Bulgular" description="SLA filtreleri, detay modalı, aksiyon geçmişi ve toplu işlemler." /><FilterBar filters={filters} setFilters={setFilters} refresh={refresh} /><BulkBar selected={selected} clear={() => setSelected(new Set())} refresh={refresh} show={show} /><FindingsTable findings={findings} selected={selected} setSelected={setSelected} onEdit={setEditing} onClose={closeFinding} onReopen={reopenFinding} onDelete={removeFinding} onDetail={setDetail} /></>; if (tab === 2) return <Paper sx={{ p: 3 }}><SectionHeader title="Bulgu Ekle" description="Yeni güvenlik bulgusunu backend API üzerinden kaydedin." /><FindingForm onSubmit={saveNew} /></Paper>; if (tab === 3) return <ExcelImportPage onImported={(r) => { show(`İçe aktarma tamamlandı: ${r.created} yeni, ${r.updated} güncellendi, ${r.failed} hatalı`, r.failed ? 'warning' : 'success'); refresh(); }} />; if (tab === 4) return <Reports findings={findings} summary={summary} />; return <LogsPage />; };
  const lastWorkTime = formatDate(summary?.last_work_time) || '-';
  return <ThemeProvider theme={theme}><CssBaseline /><Box sx={{ bgcolor: 'background.default', display: 'flex', minHeight: '100vh' }}><AppBar position="fixed" sx={{ zIndex: (muiTheme) => muiTheme.zIndex.drawer + 1 }}><Toolbar sx={{ gap: 2, minHeight: 72 }}><BrandLogo height={40} /><Box sx={{ flexGrow: 1 }}><Typography variant="h6" noWrap>Kurumsal Güvenlik Bulgu Takip</Typography><Typography variant="caption" sx={{ opacity: .78 }}>Sürat Kargo güvenlik bulgu takip ve raporlama paneli</Typography></Box><Chip label={`Son Çalışma Saati: ${lastWorkTime}`} sx={{ display: { xs: 'none', lg: 'inline-flex' }, color: '#fff', borderColor: 'rgba(255,255,255,.42)' }} variant="outlined" /><Button color="inherit" href={exportUrl()} variant="contained" sx={{ bgcolor: 'rgba(255,255,255,.15)' }}>Excel Dışa Aktar</Button></Toolbar></AppBar><Drawer variant="permanent" sx={{ width: DRAWER_WIDTH, flexShrink: 0, [`& .MuiDrawer-paper`]: { width: DRAWER_WIDTH, boxSizing: 'border-box', bgcolor: '#fff', borderRight: '1px solid rgba(15, 47, 87, 0.10)' } }}><Toolbar sx={{ minHeight: 88, justifyContent: 'center', px: 3 }}><BrandLogo height={40} /></Toolbar><Divider /><Box sx={{ p: 2 }}><Typography variant="caption" color="text.secondary" fontWeight={800} sx={{ px: 1.5, letterSpacing: .8 }}>MENÜ</Typography><List sx={{ mt: 1 }}>{navigationItems.map((item, index) => <ListItemButton key={item} selected={tab === index} onClick={() => setTab(index)} sx={{ borderRadius: 2.5, mb: .75, py: 1.15, '&.Mui-selected': { bgcolor: 'primary.main', color: 'primary.contrastText', boxShadow: '0 10px 22px rgba(15, 47, 87, .20)', '&:hover': { bgcolor: 'primary.dark' } } }}><ListItemText primary={item} secondary={index === 1 ? `${findings.length} kayıt` : index === 0 ? 'Genel görünüm' : null} primaryTypographyProps={{ fontWeight: 800 }} /></ListItemButton>)}</List></Box></Drawer><Box component="main" sx={{ flexGrow: 1, minWidth: 0 }}><Toolbar sx={{ minHeight: 72 }} /><Container maxWidth="xl" sx={{ py: 3.5 }}>{content()}</Container></Box><DetailDialog finding={detail} onClose={() => setDetail(null)} refresh={refresh} show={show} /><Dialog open={Boolean(editing)} onClose={() => setEditing(null)} maxWidth="md" fullWidth><DialogTitle>Bulgu Düzenle</DialogTitle><DialogContent dividers>{editing && <FindingForm initial={editing} onSubmit={saveEdit} submitLabel="Güncelle" />}</DialogContent><DialogActions><Button onClick={() => setEditing(null)}>Vazgeç</Button></DialogActions></Dialog><Snackbar open={Boolean(message)} autoHideDuration={6000} onClose={() => setMessage('')}><Alert severity={severity} onClose={() => setMessage('')}>{message}</Alert></Snackbar></Box></ThemeProvider>;
}

createRoot(document.getElementById('root')).render(<App />);
